
# 1단계: 빌드 이미지
FROM node:20-alpine AS build

RUN mkdir -p /app

# 작업 디렉토리 설정
WORKDIR /app

# 패키지 설치
COPY package.json package-lock.json ./
RUN npm install

# 애플리케이션 소스 복사
COPY . .

# 애플리케이션 빌드
RUN npm run build

#명시
EXPOSE 3000
ENV PORT 3000
CMD ["npm","start"]
